[program:daytona]
command=/usr/local/bin/daytona --interval 5
priority=55
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stdout_logfile_backups=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
stderr_logfile_backups=0
user=x
environment=DAYTONA_DAEMON_LOG_FILE_PATH="/tmp/daytona-daemon.log",DAYTONA_ENTRYPOINT_LOG_FILE_PATH="/tmp/daytona-entrypoint.log",DAYTONA_USER_HOME_AS_WORKDIR="true",LOG_LEVEL="info"
