[program:dbus-session]
environment=HOME="/home/%(ENV_USER)s",USER="%(ENV_USER)s",DISPLAY="%(ENV_DISPLAY)s",XDG_RUNTIME_DIR="/tmp/runtime-%(ENV_USER)s"
command=/bin/sh -c "mkdir -p /tmp/runtime-%(ENV_USER)s && chown 1000:1000 /tmp/runtime-%(ENV_USER)s && chmod 700 /tmp/runtime-%(ENV_USER)s && export XDG_RUNTIME_DIR=/tmp/runtime-%(ENV_USER)s && rm -f /tmp/dbus-session-bus && exec /usr/bin/dbus-daemon --session --nofork --address=unix:path=/tmp/dbus-session-bus"
autostart=true
autorestart=true
priority=815
user=%(ENV_USER)s
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stdout_logfile_backups=0
redirect_stderr=true
