[program:fcitx5]
environment=HOME="/home/x",USER="x",DISPLAY=":99",DBUS_SESSION_BUS_ADDRESS="unix:path=/tmp/dbus-session-bus",XDG_RUNTIME_DIR="/tmp/runtime-x",GTK_IM_MODULE="fcitx",QT_IM_MODULE="fcitx",XMODIFIERS="@im=fcitx"
command=/usr/bin/fcitx5 --replace
autostart=true
autorestart=true
priority=820
user=x
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stdout_logfile_backups=0
redirect_stderr=true
