[program:nginx]
command=/opt/gem/nginx-wait.sh
environment=WAIT_PORTS="%(ENV_BROWSER_REMOTE_DEBUGGING_PORT)s"
autorestart=true
priority=850
user=x
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=10MB
stdout_logfile_backups=10
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=10MB
stderr_logfile_backups=10
