[program:nginx]
command=/opt/gem/nginx-wait.sh
environment=WAIT_PORTS="%(ENV_BROWSER_REMOTE_DEBUGGING_PORT)s",WAIT_FAST_PORTS="18081"
autorestart=true
priority=850
user=x
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stdout_logfile_backups=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
stderr_logfile_backups=0
